in-memory-version created
AugustsKir/flight-planner pull request #1
Opened 2022-11-16 18:15 UTC by AugustsKir

2022-11-20 10:30 UTC, janistumpelis requested changes
Paldies, ir tīri ok, bet šis tas jāpielabo. Būs vēl pāris sīkumi (man īsti nepatīk, ka datums un laiks tiek glabāts kā string beigās) bet pagaidām pielabo šos.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightAdminController.java
> +    public String handleBadInput() {
Kā šī metode īsti tiek izmantota?

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightAdminController.java
> +        this.flightService.deleteFlight(id);
Skatoes ka kādā vietā lieto this, kādā nē - teorētiski viņš nav nepieciešams, attiecīgi visu vari noņemt (izņemot, protams, konstruktorā).

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/config/WebSecurity.java
> +    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
Nu šis ir tā slideni, bet nu var atstāt... :D Laikam sanāk, ka es pateicis, ka viss zem admin-api  ir ar paroli, bet viss pārējais ir bez. Tas šajā gadījumā strādā pilnībā korekit, bet ir jauzmanās - ja pievieno jaunu kaut kādu path - tas automātiski būs bez paroles - labāk ir konfigurēt otrādāk - visam parole un tikai atsevišķām lietām nav. Bet nu - vari atstāt arī šādi.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightRepo.java
> +    private Airport RIX = new Airport("Latvia", "Riga", "RIX");
Kāpēc te jau ir kaut kādi dati?

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightRepo.java
> +    public void deleteFlight(@PathVariable String id) {
Iekš repository @PathVariable anotācija noteikti nav vajadzīga - to lieto tikai iekš controller.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightAdminController.java
> +    public void deleteFlight(@PathVariable String id) {
Varbūt saņem šeit uzreiz Integer nevis String? Manuprāt, tas daudzkur novienkāršos kodu.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightAdminController.java
> +    public Flight getFlight(@PathVariable String id) {
Te arī uzreiz Integer.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightService.java
> +        int size = this.repository.flightList.stream().filter(f -> f.equals(flight)).toList().size();
Var izmantot Stream iebūvēto anyMatch - uzreiz pārbauda vai kāds atbilst kritērijam un atgriež boolean, nav tad tas size jāpārbauda.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightService.java
> +    public void deleteFlight(@PathVariable String id) {
Te arī to PathVariable nevajag.

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightService.java
> +            throw new ResponseStatusException(HttpStatus.I_AM_A_TEAPOT);
Tiešām te vajadzēja būt tādam HttpStatus? :)

2022-11-20 10:30 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/FlightService.java
> +            Date arrival = formatter.parse(flight.getArrivalTime());
Vecos javas Date noteikti neizmantojam, tikai un vienīgi LocalDateTime un tamlīdzīgos.

2022-11-26 06:50 UTC, janistumpelis approved these changes
Lieku approve, lai vari mērdžot bet obligāti jānomaina datu tips uz LocalDateTime flight klasē.

2022-11-26 06:50 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flightmanager/domain/Flight.java
> +    private final String departureTime;
DepartureTime un arrivalTime jāliek kā LocalDateTime, savādāk tas neies kopā ar datu bāzi.

2022-11-27 19:32 UTC, AugustsKir commented on src/main/java/io/codelex/flightplanner/flightmanager/domain/Flight.java
> +    private final String departureTime;
tiks izdarīts

2022-11-27 19:33 UTC, merged